"""Build the offline corpus the studio runs against.

WHAT THIS IS. A seeded, synthetic metagenome. Every sequence in it is
generated by the evolution simulator in :mod:`studio.corpus.evolve`; none is a
natural sequence, and nothing here should be mistaken for data. It exists so
the pipeline can be executed and scored in an environment with no access to
UniProt, NCBI or the EBI, and so the test suite has a ground truth to score
against. Point the studio at :class:`studio.sources.live.LiveSource` and the
same stages run against the real databases.

WHAT IS PLANTED. Three things, and the pipeline is told about only the first:

* instances of the described systems in ``known_systems.yaml`` -- these are
  "public knowledge" and the ``reproduce`` stage must recover them before the
  campaign is allowed to continue;
* two genuinely novel architectures, whose locations are withheld from every
  stage and revealed only by ``studio score``; and
* a set of decoys, each built to be attractive to a naive search and killed by
  a specific check the triage stage is supposed to perform.

The decoys are the point. A pipeline that finds the planted novel systems but
also promotes the decoys has not demonstrated anything: the article's workflow
is defined by how much it throws away.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from pathlib import Path

import numpy as np

from ..bio.seq import revcomp
from .evolve import EvolvedSequence, FamilyModel, evolve_family, make_family

# Lineage strings used to give the corpus a taxonomy the spread statistics can
# actually measure. Phage lineages matter: the article's system was found in
# bacteriophages.
LINEAGES = [
    "Bacteria;Pseudomonadota;Gammaproteobacteria;Enterobacterales",
    "Bacteria;Pseudomonadota;Betaproteobacteria;Burkholderiales",
    "Bacteria;Bacillota;Bacilli;Lactobacillales",
    "Bacteria;Bacillota;Clostridia;Eubacteriales",
    "Bacteria;Actinomycetota;Actinomycetes;Mycobacteriales",
    "Bacteria;Bacteroidota;Bacteroidia;Bacteroidales",
    "Bacteria;Cyanobacteriota;Cyanophyceae;Synechococcales",
    "Viruses;Uroviricota;Caudoviricetes;Peduovirales",
    "Viruses;Uroviricota;Caudoviricetes;Crassvirales",
    "Viruses;Uroviricota;Caudoviricetes;unclassified-siphovirus",
]
PHAGE_LINEAGES = [lin for lin in LINEAGES if lin.startswith("Viruses")]


@dataclass
class CorpusGene:
    gene_id: str
    contig_id: str
    start: int
    end: int
    strand: int
    protein: str
    family: str
    annotation: str = ""


@dataclass
class CorpusArray:
    array_id: str
    contig_id: str
    start: int
    end: int
    repeat: str
    n_copies: int
    spacer_len: int


@dataclass
class CorpusContig:
    contig_id: str
    dna: str
    lineage: str
    source: str = "synthetic-metagenome"


@dataclass
class PlantedSystem:
    """Ground truth for one planted locus. Withheld from every pipeline stage."""

    locus_id: str
    contig_id: str
    anchor_gene: str
    system_id: str          # catalogue id, or "novel:<name>", or "decoy:<why>"
    is_novel: bool
    should_survive_triage: bool
    kill_reason: str = ""   # for decoys: the check that is supposed to catch it


@dataclass
class Corpus:
    contigs: dict[str, CorpusContig] = field(default_factory=dict)
    genes: dict[str, CorpusGene] = field(default_factory=dict)
    arrays: dict[str, CorpusArray] = field(default_factory=dict)
    truth: list[PlantedSystem] = field(default_factory=list)
    meta: dict = field(default_factory=dict)

    def genes_on(self, contig_id: str) -> list[CorpusGene]:
        return sorted(
            (g for g in self.genes.values() if g.contig_id == contig_id),
            key=lambda g: g.start,
        )

    def arrays_on(self, contig_id: str) -> list[CorpusArray]:
        return sorted(
            (a for a in self.arrays.values() if a.contig_id == contig_id),
            key=lambda a: a.start,
        )

    def proteins(self) -> dict[str, str]:
        return {g.gene_id: g.protein for g in self.genes.values()}

    # -- persistence --------------------------------------------------------

    def write(self, directory: Path) -> None:
        directory.mkdir(parents=True, exist_ok=True)
        (directory / "contigs.json").write_text(
            json.dumps({k: asdict(v) for k, v in self.contigs.items()}, indent=1)
        )
        (directory / "genes.json").write_text(
            json.dumps({k: asdict(v) for k, v in self.genes.items()}, indent=1)
        )
        (directory / "arrays.json").write_text(
            json.dumps({k: asdict(v) for k, v in self.arrays.items()}, indent=1)
        )
        (directory / "meta.json").write_text(json.dumps(self.meta, indent=1))
        # Ground truth lives in its own file. No stage reads it; only the
        # scoring command does.
        (directory / "TRUTH.withheld.json").write_text(
            json.dumps([asdict(t) for t in self.truth], indent=1)
        )

    @classmethod
    def read(cls, directory: Path, *, with_truth: bool = False) -> "Corpus":
        directory = Path(directory)
        c = cls()
        c.contigs = {
            k: CorpusContig(**v)
            for k, v in json.loads((directory / "contigs.json").read_text()).items()
        }
        c.genes = {
            k: CorpusGene(**v)
            for k, v in json.loads((directory / "genes.json").read_text()).items()
        }
        c.arrays = {
            k: CorpusArray(**v)
            for k, v in json.loads((directory / "arrays.json").read_text()).items()
        }
        c.meta = json.loads((directory / "meta.json").read_text())
        if with_truth:
            c.truth = [
                PlantedSystem(**t)
                for t in json.loads((directory / "TRUTH.withheld.json").read_text())
            ]
        return c


# --- family definitions ------------------------------------------------------


def _families(rng: np.random.Generator) -> dict[str, FamilyModel]:
    """Progenitors for every protein family in the corpus.

    The RT progenitor carries the motif A / motif C geometry the studio's motif
    model looks for, held invariant so that every descendant is a genuine
    catalytic RT unless a decoy deliberately breaks it.
    """
    fams: dict[str, FamilyModel] = {}

    # Reverse transcriptase: ~330 aa, motif A at 118, motif C (YADD) at 196.
    # The A->C gap of ~74 residues sits inside the 40-180 window the motif model
    # allows, and both are rate-0 so they survive every branch.
    fams["RT"] = make_family(
        "RT", 330, rng,
        motifs=[(118, "LVDIDLKDFF"), (160, "KRLIVSKLQ"), (196, "YADDFVIF"), (240, "LGFLGYKF")],
        conserved_spans=[(100, 140), (185, 215), (230, 255)],
        loop_spans=[(0, 60), (270, 330)],
    )

    # Partner and accessory families. Each gets its own invariant signature so
    # that the search stage can label neighbours reliably without a real Pfam.
    partners = {
        "retron_effector": (240, "HNHQCLKGCD", 90),
        "cas1":            (300, "DRFWGEHLLQ", 120),
        "cas2":            (95,  "FVLVAYDIS", 30),
        "cas6":            (230, "RGWLRRFFDT", 80),
        "avd":             (130, "PQKRLAEMLR", 45),
        "abi_partner":     (200, "WDNKLLTGHY", 70),
        "maturase_x":      (170, "TGIPQGGILS", 60),
        "he_endonuclease": (150, "LAGLIDGDGY", 55),
        "dgr_target":      (260, "NVSNVNVSNV", 95),
    }
    for name, (length, motif, pos) in partners.items():
        fams[name] = make_family(
            name, length, rng,
            motifs=[(pos, motif)],
            conserved_spans=[(max(0, pos - 25), min(length, pos + 35))],
            loop_spans=[(0, 30)],
        )

    # The novel partner: an uncharacterised protein family with no described
    # relationship to any system in the catalogue.
    fams["unk_partner"] = make_family(
        "unk_partner", 155, rng,
        motifs=[(60, "CWACGKPHRC"), (110, "EEWLRRQLD")],
        conserved_spans=[(50, 130)],
        loop_spans=[(0, 40)],
    )
    fams["unk_partner_b"] = make_family(
        "unk_partner_b", 190, rng,
        motifs=[(75, "GTKSRRWQHE")],
        conserved_spans=[(60, 120)],
        loop_spans=[(0, 45)],
    )

    # Phage and housekeeping background.
    for name, length in [
        ("terminase", 420), ("portal", 380), ("capsid", 330), ("tail_fibre", 480),
        ("lysin", 180), ("integrase", 340), ("helicase", 400), ("methyltransferase", 290),
        ("hypothetical_a", 120), ("hypothetical_b", 210), ("hypothetical_c", 165),
        ("transposase", 300), ("toxin", 140), ("antitoxin", 95),
    ]:
        fams[name] = make_family(
            name, length, rng,
            conserved_spans=[(length // 3, 2 * length // 3)],
            loop_spans=[(0, length // 6)],
        )
    return fams


# --- DNA assembly ------------------------------------------------------------

_CODON_CHOICES: dict[str, list[str]] = {}


def _reverse_translate(protein: str, rng: np.random.Generator) -> str:
    """Back-translate a protein with random synonymous codon choice.

    Contigs must be real DNA because the repeat-array detector and the GC/codon
    checks operate on nucleotides, not on the protein layer.
    """
    global _CODON_CHOICES
    if not _CODON_CHOICES:
        from ..bio.seq import CODON_TABLE
        for codon, aa in CODON_TABLE.items():
            _CODON_CHOICES.setdefault(aa, []).append(codon)
    out = ["ATG"]
    for aa in protein[1:]:
        choices = _CODON_CHOICES.get(aa) or _CODON_CHOICES["A"]
        out.append(choices[int(rng.integers(0, len(choices)))])
    out.append(["TAA", "TGA", "TAG"][int(rng.integers(0, 3))])
    return "".join(out)


def _intergenic(rng: np.random.Generator, lo: int, hi: int) -> str:
    n = int(rng.integers(lo, hi + 1))
    return "".join(rng.choice(list("ACGT"), size=n)) if n else ""


def _make_array_dna(
    rng: np.random.Generator,
    n_copies: int,
    repeat_len: int,
    spacer_len: int,
    *,
    spacer_jitter: int = 2,
    repeat_mismatch: float = 0.03,
    identical_spacers: bool = False,
) -> tuple[str, str]:
    """Build a repeat-spacer array; returns ``(dna, repeat_consensus)``."""
    repeat = "".join(rng.choice(list("ACGT"), size=repeat_len))
    fixed_spacer = "".join(rng.choice(list("ACGT"), size=spacer_len))
    chunks: list[str] = []
    for i in range(n_copies):
        unit = list(repeat)
        for j in range(len(unit)):
            if rng.random() < repeat_mismatch:
                unit[j] = str(rng.choice(list("ACGT")))
        chunks.append("".join(unit))
        if i < n_copies - 1:
            if identical_spacers:
                chunks.append(fixed_spacer)
            else:
                n = max(12, spacer_len + int(rng.integers(-spacer_jitter, spacer_jitter + 1)))
                chunks.append("".join(rng.choice(list("ACGT"), size=n)))
    return "".join(chunks), repeat


@dataclass
class _Slot:
    """One element to lay down on a contig, in order."""

    kind: str                  # "gene" or "array"
    family: str = ""
    strand: int = 1
    gap_before: tuple[int, int] = (20, 55)
    protein: str = ""
    array_spec: dict | None = None


class _ContigWriter:
    """Lays slots out on a contig and records coordinates."""

    def __init__(self, corpus: Corpus, contig_id: str, lineage: str, rng: np.random.Generator):
        self.corpus = corpus
        self.contig_id = contig_id
        self.lineage = lineage
        self.rng = rng
        self.parts: list[str] = []
        self.cursor = 0
        self.gene_ids: list[str] = []
        self.array_ids: list[str] = []

    def _emit(self, dna: str) -> tuple[int, int]:
        start = self.cursor
        self.parts.append(dna)
        self.cursor += len(dna)
        return start, self.cursor

    def pad(self, lo: int, hi: int) -> None:
        self._emit(_intergenic(self.rng, lo, hi))

    def gene(self, family: str, protein: str, strand: int, annotation: str = "") -> str:
        dna = _reverse_translate(protein, self.rng)
        if strand == -1:
            dna = revcomp(dna)
        start, end = self._emit(dna)
        gene_id = f"{self.contig_id}_g{len(self.gene_ids):03d}"
        self.corpus.genes[gene_id] = CorpusGene(
            gene_id=gene_id, contig_id=self.contig_id, start=start, end=end,
            strand=strand, protein=protein, family=family, annotation=annotation,
        )
        self.gene_ids.append(gene_id)
        return gene_id

    def array(self, **spec) -> str:
        dna, repeat = _make_array_dna(self.rng, **spec)
        start, end = self._emit(dna)
        array_id = f"{self.contig_id}_a{len(self.array_ids):02d}"
        self.corpus.arrays[array_id] = CorpusArray(
            array_id=array_id, contig_id=self.contig_id, start=start, end=end,
            repeat=repeat, n_copies=spec["n_copies"], spacer_len=spec["spacer_len"],
        )
        self.array_ids.append(array_id)
        return array_id

    def finish(self, source: str = "synthetic-metagenome") -> None:
        self.corpus.contigs[self.contig_id] = CorpusContig(
            contig_id=self.contig_id, dna="".join(self.parts),
            lineage=self.lineage, source=source,
        )


# --- reference proteins ------------------------------------------------------
#
# The studio labels a neighbouring gene by homology to a reference set. That set
# covers the families the literature describes -- every family named in
# known_systems.yaml, plus common phage and housekeeping genes. It deliberately
# does NOT contain the novel partner families: a gene with no reference match is
# labelled "unk", which is the state the search stage is looking for.

DESCRIBED_FAMILIES = [
    "RT", "retron_effector", "cas1", "cas2", "cas6", "avd", "abi_partner",
    "maturase_x", "he_endonuclease", "dgr_target",
    "terminase", "portal", "capsid", "tail_fibre", "lysin", "integrase",
    "helicase", "methyltransferase", "hypothetical_a", "hypothetical_b",
    "hypothetical_c", "transposase", "toxin", "antitoxin",
]

NOVEL_FAMILIES = ["unk_partner", "unk_partner_b"]


class _Pool:
    """Draws evolved members of a family without replacement, refilling as needed."""

    def __init__(self, leaves: list[EvolvedSequence], rng: np.random.Generator):
        self.leaves = leaves
        self.rng = rng
        self._order = list(rng.permutation(len(leaves)))

    def draw(self) -> EvolvedSequence:
        if not self._order:
            self._order = list(self.rng.permutation(len(self.leaves)))
        return self.leaves[self._order.pop()]


def _break_triad(protein: str) -> str:
    """Substitute the motif C aspartate pair, producing a catalytically dead RT."""
    import re
    m = list(re.finditer(r"[YF].DD", protein))
    if not m:
        return protein
    hit = m[-1]
    return protein[:hit.start() + 2] + "NN" + protein[hit.end():]


def build_corpus(
    *,
    seed: int = 20240917,
    n_background_contigs: int = 120,
    scale: float = 1.0,
) -> Corpus:
    """Generate the corpus. ``scale`` shrinks every instance count for fast tests."""
    rng = np.random.default_rng(seed)
    corpus = Corpus()
    fams = _families(rng)

    def n(x: int) -> int:
        return max(1, int(round(x * scale)))

    # Evolve a pool for each family. The RT pool is deep because every planted
    # system draws its anchor from it -- which is what makes the described and
    # the novel systems share one genuine family history, as they must.
    pools: dict[str, _Pool] = {}
    depth = {"RT": n(260)}
    for name, model in fams.items():
        k = depth.get(name, n(60))
        pools[name] = _Pool(evolve_family(model, k, rng, lineages=LINEAGES), rng)

    contig_no = 0

    def new_contig(lineage: str) -> _ContigWriter:
        nonlocal contig_no
        contig_no += 1
        w = _ContigWriter(corpus, f"ctg{contig_no:05d}", lineage, rng)
        w.pad(300, 1200)
        return w

    def filler(w: _ContigWriter, k: int) -> None:
        for _ in range(k):
            fam = str(rng.choice(
                ["hypothetical_a", "hypothetical_b", "hypothetical_c", "helicase",
                 "methyltransferase", "capsid", "portal", "tail_fibre", "lysin",
                 "integrase", "terminase", "toxin", "antitoxin", "transposase"]
            ))
            w.pad(60, 400)
            w.gene(fam, pools[fam].draw().sequence, int(rng.choice([1, -1])))

    def plant(
        *,
        system_id: str,
        lineages: list[str],
        layout: list[_Slot],
        is_novel: bool,
        survives: bool,
        kill_reason: str = "",
        count: int,
        distant_array: dict | None = None,
    ) -> None:
        """Lay out ``count`` instances of one architecture on fresh contigs."""
        for _ in range(count):
            lineage = str(rng.choice(lineages))
            w = new_contig(lineage)
            filler(w, int(rng.integers(1, 3)))
            w.pad(400, 900)

            anchor: str | None = None
            for slot in layout:
                w.pad(*slot.gap_before)
                if slot.kind == "array":
                    w.array(**(slot.array_spec or {}))
                    continue
                protein = slot.protein or pools[slot.family].draw().sequence
                gid = w.gene(slot.family, protein, slot.strand)
                if slot.family == "RT" and anchor is None:
                    anchor = gid

            if distant_array:
                # Deliberately far outside the neighbourhood window.
                w.pad(*distant_array.pop("gap", (9000, 11000)))
                w.array(**distant_array)

            w.pad(300, 800)
            filler(w, int(rng.integers(1, 3)))
            w.finish()

            if anchor:
                corpus.truth.append(PlantedSystem(
                    locus_id=f"{w.contig_id}:{anchor}",
                    contig_id=w.contig_id,
                    anchor_gene=anchor,
                    system_id=system_id,
                    is_novel=is_novel,
                    should_survive_triage=survives,
                    kill_reason=kill_reason,
                ))

    G = _Slot  # brevity in the layouts below

    crispr = dict(n_copies=0, repeat_len=30, spacer_len=34)

    def arr(copies: int, repeat_len: int = 30, spacer_len: int = 34, **kw) -> dict:
        d = dict(crispr)
        d.update(n_copies=copies, repeat_len=repeat_len, spacer_len=spacer_len)
        d.update(kw)
        return d

    # --- described systems: the reproduce stage must recover these -----------

    plant(system_id="retron", lineages=LINEAGES, count=n(38), is_novel=False, survives=False,
          kill_reason="described system (retron)",
          layout=[G("gene", "RT"), G("gene", "retron_effector", gap_before=(15, 40))])

    plant(system_id="group_ii_intron", lineages=LINEAGES, count=n(30), is_novel=False,
          survives=False, kill_reason="described system (group II intron)",
          layout=[G("gene", "RT"), G("gene", "maturase_x", gap_before=(10, 30))])

    plant(system_id="dgr", lineages=LINEAGES, count=n(24), is_novel=False, survives=False,
          kill_reason="described system (DGR)",
          layout=[G("gene", "RT"), G("gene", "avd", gap_before=(15, 45)),
                  G("gene", "dgr_target", gap_before=(20, 50))])

    plant(system_id="rt_cas1", lineages=LINEAGES, count=n(28), is_novel=False, survives=False,
          kill_reason="described system (RT-Cas1)",
          layout=[G("gene", "cas1"), G("gene", "RT", gap_before=(10, 35)),
                  G("gene", "cas2", gap_before=(10, 35)),
                  G("array", array_spec=arr(int(rng.integers(6, 16))), gap_before=(80, 260))])

    plant(system_id="abi_rt", lineages=LINEAGES, count=n(22), is_novel=False, survives=False,
          kill_reason="described system (Abi RT)",
          layout=[G("gene", "RT"), G("gene", "abi_partner", gap_before=(12, 40))])

    plant(system_id="unclassified_rt", lineages=LINEAGES, count=n(36), is_novel=False,
          survives=False, kill_reason="lone RT, no system to propose",
          layout=[G("gene", "RT")])

    # --- the planted novel systems -------------------------------------------
    #
    # NOVEL-1 mirrors the architecture in the article: the enzyme, a partner
    # gene of unknown function beside it, and a long array of evenly spaced
    # repeats. Planted in phage lineages, conserved across several of them.

    for _ in range(n(15)):
        plant(system_id="novel:ART-like", lineages=PHAGE_LINEAGES, count=1,
              is_novel=True, survives=True,
              layout=[G("gene", "RT"),
                      G("gene", "unk_partner", gap_before=(8, 30)),
                      G("array", array_spec=arr(int(rng.integers(9, 22)),
                                                repeat_len=int(rng.integers(29, 33)),
                                                spacer_len=int(rng.integers(34, 39))),
                        gap_before=(60, 200))])

    # NOVEL-2: a novel partner with no non-coding component. Genuinely
    # undescribed, but with one fewer line of evidence -- it exists so the
    # triage stage has to rank, not merely accept or reject.
    plant(system_id="novel:orphan-partner", lineages=LINEAGES[:6], count=n(10),
          is_novel=True, survives=True,
          layout=[G("gene", "RT"), G("gene", "unk_partner_b", gap_before=(10, 35))])

    # --- decoys: each one is a specific check the triage stage must perform ---

    dead_rt = [_break_triad(pools["RT"].draw().sequence) for _ in range(n(6))]
    for protein in dead_rt:
        plant(system_id="decoy:dead-rt", lineages=PHAGE_LINEAGES, count=1,
              is_novel=False, survives=False,
              kill_reason="motif C aspartate pair substituted: catalytically dead",
              layout=[G("gene", "RT", protein=protein),
                      G("gene", "unk_partner", gap_before=(8, 30)),
                      G("array", array_spec=arr(int(rng.integers(9, 18))),
                        gap_before=(60, 200))])

    for _ in range(n(6)):
        frag = pools["RT"].draw().sequence
        plant(system_id="decoy:rt-fragment", lineages=PHAGE_LINEAGES, count=1,
              is_novel=False, survives=False,
              kill_reason="RT fragment: does not cover the profile's core columns",
              layout=[G("gene", "RT", protein=frag[150:265]),
                      G("gene", "unk_partner", gap_before=(8, 30)),
                      G("array", array_spec=arr(int(rng.integers(9, 18))),
                        gap_before=(60, 200))])

    # These two decoys carry NO conserved partner. An earlier version gave them
    # the same partner family as the planted novel system, which made them
    # genuine RT-plus-conserved-unknown loci that merely happened to have a bad
    # array -- promoting those was arguably correct, so they tested nothing.
    # A decoy is only a decoy if the feature under test is its sole apparent
    # evidence.
    plant(system_id="decoy:distant-array", lineages=PHAGE_LINEAGES, count=n(6),
          is_novel=False, survives=False,
          kill_reason="array is ~10 kb away: not co-located with the operon",
          layout=[G("gene", "RT")],
          distant_array=dict(arr(int(rng.integers(8, 16))), gap=(9000, 11000)))

    plant(system_id="decoy:vntr", lineages=PHAGE_LINEAGES, count=n(6),
          is_novel=False, survives=False,
          kill_reason="repeats have near-identical spacers: a VNTR, not a spacer array",
          layout=[G("gene", "RT"),
                  G("array", array_spec=arr(int(rng.integers(8, 14)),
                                            identical_spacers=True),
                    gap_before=(60, 200))])

    # A partner family seen at exactly one locus: nothing to distinguish it from
    # a chance neighbour.
    singleton = make_family("singleton_partner", 165, rng,
                            motifs=[(70, "MQWDRTKPLA")],
                            conserved_spans=[(55, 110)], loop_spans=[(0, 30)])
    pools["singleton_partner"] = _Pool(evolve_family(singleton, 4, rng, lineages=LINEAGES), rng)
    # Two instances, deliberately below the three-independent-loci minimum an
    # association claim requires. At exactly three it would sit on the
    # threshold and test nothing.
    plant(system_id="decoy:singleton-partner", lineages=PHAGE_LINEAGES, count=2,
          is_novel=False, survives=False,
          kill_reason="partner gene occurs at a single locus: association is not conserved",
          layout=[G("gene", "singleton_partner", gap_before=(8, 30)),
                  G("gene", "RT"),
                  G("array", array_spec=arr(int(rng.integers(8, 16))), gap_before=(60, 200))])

    # A deeply diverged cas1 that a strict label threshold will call "unk". The
    # locus then looks like a novel RT+unknown+array system and is in fact an
    # RT-Cas1 adaptation module. Only a sensitive homology search catches it.
    diverged = evolve_family(fams["cas1"], n(8), rng, max_depth=3.2, lineages=LINEAGES,
                             id_prefix="cas1div")
    pools["cas1_diverged"] = _Pool(diverged, rng)
    plant(system_id="decoy:diverged-cas1", lineages=LINEAGES, count=n(6),
          is_novel=False, survives=False,
          kill_reason="the 'unknown' partner is a diverged Cas1: this is an RT-Cas1 system",
          layout=[G("gene", "cas1_diverged", gap_before=(8, 30)),
                  G("gene", "RT"),
                  G("gene", "cas2", gap_before=(10, 35)),
                  G("array", array_spec=arr(int(rng.integers(7, 15))), gap_before=(80, 240))])

    # --- background ----------------------------------------------------------

    for _ in range(n_background_contigs):
        w = new_contig(str(rng.choice(LINEAGES)))
        filler(w, int(rng.integers(3, 9)))
        # A minority of background contigs carry an unrelated CRISPR array, so
        # "has an array" is not by itself an unusual observation.
        if rng.random() < 0.18:
            w.pad(200, 600)
            w.array(**arr(int(rng.integers(4, 12))))
            filler(w, int(rng.integers(1, 4)))
        w.finish()

    corpus.meta = {
        "synthetic": True,
        "generator": "studio.corpus.build.build_corpus",
        "seed": seed,
        "scale": scale,
        "warning": (
            "Every sequence in this corpus is simulated. It exists so the "
            "pipeline can run and be scored offline; it is not data and no "
            "biological conclusion may be drawn from it."
        ),
        "described_families": DESCRIBED_FAMILIES,
        "n_contigs": len(corpus.contigs),
        "n_genes": len(corpus.genes),
        "n_arrays": len(corpus.arrays),
        "n_planted": len(corpus.truth),
    }

    # Reference proteins for the described families only. Withholding the novel
    # partner families is what leaves them labelled "unk" downstream.
    corpus.meta["references"] = {
        fam: pools[fam].draw().sequence
        for fam in DESCRIBED_FAMILIES if fam in pools
    }
    return corpus
