"""A sequence evolution simulator, used to build the offline corpus.

The studio's pipeline is the deliverable; the corpus is scaffolding that lets
the pipeline run and be scored where the real sequence databases are not
reachable. For that scaffolding to be worth anything, the homology in it has to
be *earned* -- generated by descent with modification, not by sprinkling random
mutations on a template. Otherwise a profile search that succeeds proves only
that the generator and the search agree.

So families here are evolved along a random tree under a substitution model
whose exchangeabilities come from BLOSUM62, with site-specific rates: catalytic
positions are held nearly fixed, structural positions drift slowly, and loops
drift fast. The result has the properties real families have -- graded
identity, conserved motifs inside variable backgrounds, indels in loops -- and
is therefore a fair test of a homology search.

Nothing generated here is a natural sequence. Corpora built with this module
are labelled synthetic wherever they are written to disk.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field

import numpy as np

from ..bio.align import BLOSUM62
from ..bio.seq import AA, AA_INDEX, BACKGROUND_AA

_BG = np.array([BACKGROUND_AA[a] for a in AA], dtype=np.float64)
_BG /= _BG.sum()


def _exchange_matrix(temperature: float = 1.0) -> np.ndarray:
    """Row-stochastic substitution probabilities from BLOSUM62 log-odds.

    ``P(b|a) ∝ background(b) * 2^(BLOSUM62[a,b] / temperature)`` recovers the
    target frequencies the matrix was derived from, so substitutions are
    conservative in the way real ones are: a leucine is far more likely to
    become isoleucine than tryptophan.
    """
    s = BLOSUM62[:20, :20].astype(np.float64)
    p = _BG[None, :] * np.power(2.0, s / temperature)
    np.fill_diagonal(p, 0.0)  # the diagonal is handled by the mutation rate
    return p / p.sum(axis=1, keepdims=True)


EXCHANGE = _exchange_matrix()

# Cumulative forms: sampling a substitution is a uniform draw plus a binary
# search, which is an order of magnitude cheaper than rng.choice(p=...) inside
# the per-residue loop that generates the whole corpus.
_EXCHANGE_CUM = np.cumsum(EXCHANGE, axis=1)
_BG_CUM = np.cumsum(_BG)


def _sample(cum: np.ndarray, u: float) -> int:
    return int(np.searchsorted(cum, u * cum[-1]))


@dataclass
class SiteClass:
    """A stretch of a protein with its own evolutionary rate."""

    start: int
    end: int
    rate: float          # relative substitution rate; 0 = invariant
    indel: float = 0.0   # per-site probability of an indel per unit branch


@dataclass
class FamilyModel:
    """A progenitor sequence plus the rates that govern how it diversifies."""

    name: str
    progenitor: str
    sites: list[SiteClass] = field(default_factory=list)
    default_rate: float = 1.0
    default_indel: float = 0.004

    def rate_vector(self) -> np.ndarray:
        r = np.full(len(self.progenitor), self.default_rate, dtype=np.float64)
        for sc in self.sites:
            r[sc.start:sc.end] = sc.rate
        return r

    def indel_vector(self) -> np.ndarray:
        v = np.full(len(self.progenitor), self.default_indel, dtype=np.float64)
        for sc in self.sites:
            v[sc.start:sc.end] = sc.indel
        return v


def evolve(
    seq: str,
    branch: float,
    rates: np.ndarray,
    indels: np.ndarray,
    rng: np.random.Generator,
) -> tuple[str, np.ndarray, np.ndarray]:
    """Evolve ``seq`` along one branch, returning the descendant and its rates.

    ``branch`` is the expected number of substitutions per unit-rate site. Rate
    and indel vectors travel with the sequence so that a catalytic position
    stays catalytic in every descendant, and so that an indel in a loop does not
    silently shift the conserved positions out of register.
    """
    out: list[str] = []
    out_rates: list[float] = []
    out_indels: list[float] = []

    for i, aa in enumerate(seq):
        r, d = float(rates[i]), float(indels[i])

        # Deletion.
        if d > 0 and rng.random() < 1.0 - math.exp(-d * branch):
            continue

        idx = AA_INDEX.get(aa, 20)
        if idx < 20 and r > 0:
            # Probability of at least one substitution over the branch.
            if rng.random() < 1.0 - math.exp(-r * branch):
                aa = AA[_sample(_EXCHANGE_CUM[idx], rng.random())]
        out.append(aa)
        out_rates.append(r)
        out_indels.append(d)

        # Insertion into a loop: sampled from the background composition.
        if d > 0 and rng.random() < 0.5 * (1.0 - math.exp(-d * branch)):
            n = int(rng.integers(1, 4))
            for _ in range(n):
                out.append(AA[_sample(_BG_CUM, rng.random())])
                out_rates.append(max(r, 1.5))
                out_indels.append(max(d, 0.01))

    return "".join(out), np.array(out_rates), np.array(out_indels)


@dataclass
class EvolvedSequence:
    """One leaf of a simulated family tree."""

    seq_id: str
    sequence: str
    family: str
    depth: float           # total branch length from the progenitor
    lineage: str = ""


def evolve_family(
    model: FamilyModel,
    n_leaves: int,
    rng: np.random.Generator,
    *,
    max_depth: float = 1.2,
    lineages: list[str] | None = None,
    id_prefix: str | None = None,
) -> list[EvolvedSequence]:
    """Evolve ``n_leaves`` descendants along a random binary tree.

    Branch lengths are drawn so the leaves span a range of divergences: some
    pairs sit near 80% identity, others below 30%. A search that only recovers
    the easy half of such a family is visibly incomplete, which is what makes
    the ``reproduce`` stage's recall number informative.
    """
    prefix = id_prefix or model.name
    frontier: list[tuple[str, np.ndarray, np.ndarray, float]] = [
        (model.progenitor, model.rate_vector(), model.indel_vector(), 0.0)
    ]
    while len(frontier) < n_leaves:
        i = int(rng.integers(0, len(frontier)))
        seq, r, d, depth = frontier.pop(i)
        for _ in range(2):
            branch = float(rng.uniform(0.02, max_depth / 3.0))
            s2, r2, d2 = evolve(seq, branch, r, d, rng)
            frontier.append((s2, r2, d2, depth + branch))

    leaves: list[EvolvedSequence] = []
    for k, (seq, r, d, depth) in enumerate(frontier[:n_leaves]):
        branch = float(rng.uniform(0.0, max_depth / 4.0))
        s2, _, _ = evolve(seq, branch, r, d, rng)
        lin = lineages[k % len(lineages)] if lineages else ""
        leaves.append(EvolvedSequence(f"{prefix}_{k:04d}", s2, model.name, depth + branch, lin))
    return leaves


# --- progenitor construction -------------------------------------------------

_HYDROPHOBIC = "AVLIMFW"
_POLAR = "STNQYCH"
_CHARGED = "DEKR"
_SMALL = "AGSTP"


def random_backbone(length: int, rng: np.random.Generator) -> str:
    """A protein-like backbone: alternating secondary-structure-ish runs.

    Uniform random sequence has a flat composition no real protein has, and
    would make the low-complexity and composition-bias checks meaningless.
    """
    out: list[str] = []
    while len(out) < length:
        style = rng.random()
        n = int(rng.integers(4, 12))
        if style < 0.35:
            pool = _HYDROPHOBIC + _SMALL
        elif style < 0.65:
            pool = _POLAR + _CHARGED
        elif style < 0.85:
            pool = AA
        else:
            pool = _SMALL + "GP"
        out.extend(rng.choice(list(pool), size=n))
    return "".join(out[:length])


def implant(backbone: str, motifs: list[tuple[int, str]]) -> str:
    """Write fixed motif strings into a backbone at given offsets."""
    s = list(backbone)
    for pos, text in motifs:
        for i, c in enumerate(text):
            if pos + i < len(s):
                s[pos + i] = c
    return "".join(s)


def make_family(
    name: str,
    length: int,
    rng: np.random.Generator,
    *,
    motifs: list[tuple[int, str]] | None = None,
    conserved_spans: list[tuple[int, int]] | None = None,
    loop_spans: list[tuple[int, int]] | None = None,
) -> FamilyModel:
    """Build a progenitor with catalytic motifs held invariant.

    ``motifs`` are written verbatim and given rate 0 so every descendant keeps
    them; ``conserved_spans`` evolve slowly (structural core) and ``loop_spans``
    fast with indels.
    """
    backbone = random_backbone(length, rng)
    if motifs:
        backbone = implant(backbone, motifs)

    sites: list[SiteClass] = []
    for start, end in (loop_spans or []):
        sites.append(SiteClass(start, end, rate=2.2, indel=0.012))
    for start, end in (conserved_spans or []):
        sites.append(SiteClass(start, end, rate=0.35, indel=0.0005))
    for pos, text in (motifs or []):
        sites.append(SiteClass(pos, pos + len(text), rate=0.0, indel=0.0))

    return FamilyModel(name=name, progenitor=backbone, sites=sites)
